### PR TITLE
Clean and standarize

### PR DESCRIPTION
**Pull request by cosarara97**
The biggest commit here is the result of running dos2unix over the source tree, to convert all files to unix line endings. Git on windows gives the option to convert on push/pull, so it shouldn't be a problem. Now, that makes this pull request look like it changed everything, so append "?w=1" to the github url to see the non-whitespace changes (https://github.com/thekaratekid552/Secret-Tool/pull/7/files?w=1).
I removed all the temporary files from text editors that were laying around, and improved compatibility with other PIL versions (which you also did, so our efforts are duplicated :P ).
Every file had a different hashbang. Now they all use the standard "/usr/bin/env python2".

### CODE REVIEW

**Comment by cosarara97** [comment]
So, want me to merge it myself?

**Comment by thekaratekid552** [comment]
I'm setting it up so that you are an admin. :)

**Comment by thekaratekid552** [comment]
I have created a new organization, G3HS and made you a co-owner. At this point in time, I don't have the time to work on this project unfortunately, but you seem even more capable than I. This was the project that I learned to code the most with, so of course it isn't the cleanest. There is only one request I make: only make changes that do not remove functionality. Anything else and it is all yours. Good luck man:)

**Comment by cosarara97** [comment]
Thanks :) I'll have no problem complying with that request.

**Comment by thekaratekid552** [comment]
Keep me updated on any progress you make, I may not have time but I do
care. That's why I jumped when I saw that you were capable of keeping it
going. Also, I give you the right to create any new threads you would like
on PokeCommunity, PHO, etc. And add yourself to the credits and stuff of
course.:)

The reason I mentioned functionality was because one time, a person
submitted a new Poké and ASCII conversion function, but it removed the
possibility to use the multi character chunks that Poké contains.

**Pull request merged**
