### PR TITLE
Stone and trade with item are swaped

### PR DESCRIPTION
**Pull request by papel**
This fixes a bug in evolution methods. Currently, it shows stone as trade with item. This change fixes the problem.

Tested with Emerald.

### CODE REVIEW

**Comment by OverLoadedPanda** [comment]
wait I'm slightly confused what does this do? What do you mean it shows stone as trade with item?

**Comment by OverLoadedPanda** [comment]
also @cosarara97 I was just checking out your profile, since I had seen you are still active on this section, and I noticed a pokemon rom hack map editor called blue spider and I was stoked to realise it had a version for mac, since i hadn't found a map editor for mac yet! And I was wondering if you could point me to a tutorial for it! Thanks heaps 😄

**Comment by cosarara** [comment]
@OverLoadedPanda send me an email to talk about other projects, this isn't really the place.
Regarding the issue, it means that it used to show evolution by stone instead of evolution by trading with an item, and trading with an item instead of stone.
Regardless, this project is pretty much abandoned at this point (as proved by the commit history). Maybe try https://github.com/Gamer2020/PokemonGameEditor on wine? I don't really know what people use these days.

**Comment by OverLoadedPanda** [comment]
@cosarara97 hay, I sent an email to the email provided in your account info (cosarara@gmail.com) and it's been like a day and a bit, not sure if I sent it to the wrong email or something... Thanks!

**Comment by cosarara** [comment]
@OverLoadedPanda well yes, it's wrong. The address in my profile is clearly "cosarara97@gmail.com", with the 97 in there.

**Comment by OverLoadedPanda** [comment]
@cosarara97 I'm terribly sorry, resending it now.

**Pull request merged**
